### ISSUE TITLE
Normal login after fail login

### ISSUE THREAD

**Issue by activekey** [cooperlyt/keycloak-phone-provider#23]
i have a problem in login with phone.
When login fails, the basic (keycloak theme) login page is displayed.
thanks

https://user-images.githubusercontent.com/113419422/189836149-083ec308-94bb-4599-b3ca-8f00931a44d0.mp4

**Comment by activekey** [comment]
answer : supportPhone in login.ftl in post request is false

**Comment by cooperlyt** [comment]
your flows config  is wrong, refer [readme](https://github.com/cooperlyt/keycloak-phone-provider/blob/master/README.md)

**Comment by tungboom** [comment]
@cooperlyt I used version keycloak-phone-provider-21.0.2_phone-2.3.3 and got the same error. I have configured as [readme](https://github.com/cooperlyt/keycloak-phone-provider/blob/master/README.md).

**Comment by tungboom** [comment]
Hi @activekey, How did you fix this?

**Comment by GLY-JeffreyTCK** [comment]
Hi any answer for this? I have same experience for this

**Comment by GLY-JeffreyTCK** [comment]
@tungboom @cooperlyt @activekey do you fix on this issue?

**Comment by tungboom** [comment]
@GLY-JeffreyTCK I have customized it with another theme and removed supportPhone. It's not necessary for me

![image](https://github.com/cooperlyt/keycloak-phone-provider/assets/23371853/51536361-ca2e-4e20-adac-4bed68a24fcb)

**Comment by GLY-JeffreyTCK** [comment]
@tungboom ok thanks for your reply. Finally i able find another solution to override challenge function to set supportPhone to true in PhoneUsernamePasswordForm.java

![Screen Shot 2024-05-04 at 17 08 08](https://github.com/cooperlyt/keycloak-phone-provider/assets/59438915/aae4896d-514e-4508-8f8e-df7eb9515c7a)
