### ISSUE TITLE
Add and verify phone number for existing email user

### ISSUE THREAD

**Issue by MekkyUA** [cooperlyt/keycloak-phone-provider#26]
I've Keycloak (Quarkus) up and running on production with thousands of users registered via email.
The email is being verified and used as username.
All users can login via email address.

My question is:

How can I use this SPI to trigger a screen for the user to add and verify his phone number as a secondary identifier or without touching his email address?

**Comment by cooperlyt** [comment]
checked "Update Phone Number" or "Configure OTP over SMS" on user required.
