### ISSUE TITLE
 Mobile number with  Password custom Provider in Keycloak 19 - mod Security blocks the form and clears from authentication tab

### ISSUE THREAD

**Issue by dhonishiva** [cooperlyt/keycloak-phone-provider#27]
Hi All, 

Have tried  implemented  mobile no authentication form flow in keycloak it was working  fine, post enabling mod security in apache server security the custom form flow got removed automatically from the realm,no logs written during the removal of phone password form inside authentication tab at the realm level.

@cooperlyt can you plz help in this regard to resolve the mod security issue with keycloak mobile custom provider. 

Help needed from you..   #HelpRequired

**Comment by cooperlyt** [comment]
Sorry, I don't know anything about `apache server security`.

**Comment by dhonishiva** [comment]
Thanks for the response @cooperlyt 
Would help as we get the forms got removed with any custom realms
Also how do check  the delete query was executed during the removal..information about the  related  tables of authentication  form

**Comment by cooperlyt** [comment]
are you connect a local database? if not , docker will be clear any data on container down!
