### ISSUE TITLE
Verify Phone Action and use API

### ISSUE THREAD

**Issue by Kowiste** [cooperlyt/keycloak-phone-provider#39]
Hi
everything is working perfectly, but I have a question of how it will be possible to update the telephone and send a email to validate this new phone?

I t will be possible use keycloak API to make the register, login, etc...?

**Comment by cooperlyt** [comment]
1.update phone number:
two ways:
+ A: set a `update phone number request`  , will be show an update form on the user next login.
+ B: change user attribute , the name is phoneNumber
2. send a email to validate this new phone?
use email validate phone? Why? 
3.  keycloak API is not change anything, you can use it,  I only add two endpoints. refer [Readme endpoints ](https://github.com/cooperlyt/keycloak-phone-provider#everybody-phone-number-if-not-exists-create-user-by-phone-number-get-access-token-use-endpoints)
