### ISSUE TITLE
Why the Two user attributes phoneNumberVerified and phoneNumber not be auto created after phone registration

### ISSUE THREAD

**Issue by longinf-com** [cooperlyt/keycloak-phone-provider#45]
Q1: After phone registered, i found the two user attributes phoneNumberVerified and phoneNumber were not auto created in table USER_ATTRIBUTE of DB?

**Comment by longinf-com** [comment]
Q2: When I use phone login, after commit phone form, one username and password form appear at once. I don't know why

**Comment by longinf-com** [comment]
2023-04-05 03:20:05,650 WARN  [org.keycloak.events] (executor-thread-22) type=LOGIN_ERROR, realmId=ec98018c-9e1d-48fa-933b-edbd873674b4, clientId=account-console, userId=null, ipAddress=115.171.22.16, error=user_not_found, auth_method=openid-connect, auth_type=code, redirect_uri=https://accounts.longxi.co/realms/longxi/account/#/, code_id=7677f61b-9428-4ea1-be45-a8ac1ee43849, authSessionParentId=7677f61b-9428-4ea1-be45-a8ac1ee43849, authSessionTabId=t0jO7iJORWg

**Comment by cooperlyt** [comment]
Q1:  
Does phoneNumberVerified and phoneNumber exist in the WEB UI?
Q2:
are you add OTP in flow? or add `Update Phone Number` or `Configure OTP over SMS` for user.
Q3:
if version > 2.2.2 , phone number must full. e.g +86XXXXXXXXXX or  set `--spi-phone-default-[$realm-]compatible=true`

**Comment by longinf-com** [comment]
@cooperlyt  
Thanks for your reply.   I'm using version 2.3.1.
In the Q1 both of phoneNumberVerified and phoneNumber don't exist in the WEB UI，and user attribute is empty.
Maybe Q1 causes Q2 and Q3. This problem puzzles me about two days.

**Comment by cooperlyt** [comment]
![未命名](https://user-images.githubusercontent.com/4219608/230074636-a373ee65-7613-40eb-acf6-0d991a136f01.jpg)

This is the user I just created by registration flow. I don't know what's happen for you

Please provide your docker-compose.yml and export you realm setting .

**Comment by cooperlyt** [comment]
I found a bug on 2.3.1 , I will fix it in 2.3.2, please wait, or use 2.2.1

**Comment by cooperlyt** [comment]
the bug only a web display error, not about your question! check your registration and browser flow settings
