### ISSUE TITLE
Login with either Phone/Otp or Username/Password in Direct Grant

### ISSUE THREAD

**Issue by vatsalumrigar** [cooperlyt/keycloak-phone-provider#46]
My need in to Login user with either Direct grant with phone or direct grant with Username and password validation, i tried using both subflows in a new flow and using both flows as Alternative of each other but i can only login through one method which is first in the flow , i need a custom condition in which if user is giving phonenumber as a credtential he can use direct grant with phone flow else if a user provides username then username and password validation flow should execute.

**Comment by cooperlyt** [comment]
I will add a conditional on 2.3.3,  
Before 2.3.3 you can use two different clients and set different flows.

**Comment by vatsalumrigar** [comment]
Okay thank you , will check for the same

**Comment by vatsalumrigar** [comment]
> Okay thank you , will check for the same

Its working , thanks

**Comment by vijayjagdish** [comment]
but not wroking through the API
