### ISSUE TITLE
Facing issues with Registration by Phone Flow

### ISSUE THREAD

**Issue by axoxymous-coder** [cooperlyt/keycloak-phone-provider#60]
Hi,

I was trying out `keycloak-phone-provider` with Keycloak v21.1.1. I configured the registration by phone flow as mentioned in the `README.md` of this respositiry. 

The screenshots for the same are shown below for reference:

![image](https://github.com/cooperlyt/keycloak-phone-provider/assets/102527788/75d0bc7e-05ef-47d8-82a9-401e3c98254f)
![image](https://github.com/cooperlyt/keycloak-phone-provider/assets/102527788/df273af9-0545-410c-80e9-9ec7ef259f50)
![image](https://github.com/cooperlyt/keycloak-phone-provider/assets/102527788/87525e09-19ed-41c5-ae4d-5ca97effafb1)

Also, I had disabled `Email As UserName` feature and I added the two attributes for users: `phoneNumber` and `phoneNumberVerfiied`. 

![image](https://github.com/cooperlyt/keycloak-phone-provider/assets/102527788/d51620e4-8224-409a-8e84-51b778d29494)
<img width="1527" alt="image" src="https://github.com/cooperlyt/keycloak-phone-provider/assets/102527788/b5f11311-4a83-45b8-aeb8-18003eeca938">

Now, when I try to register a new user using Phone number, although the registration is successful and username is persisted in DB with the phone number but the two attributes `phoneNumber`. and `phoneNumberVerified` are not persisted in the DB. Because of this when the new user tries to login using Phone Number, the Keycloak returns a LOGIN_ERROR with `user not found`

I am using the latest `master` branch of `keycloak-phone-provider` with Keycloak v21.1.1

Any help will be highly appreciated.

**Comment by cooperlyt** [comment]
phoneNumber and phoneNumberVerfiied  is not `User profile` , is user attribute.
