### ISSUE TITLE
User not exists when registered by phone

### ISSUE THREAD

**Issue by Jeff-Tian** [cooperlyt/keycloak-phone-provider#94]
Hi, is there any example of configuring the register by phone?

I configured the following:

<img width="1335" alt="image" src="https://github.com/cooperlyt/keycloak-phone-provider/assets/3367820/edd8afe2-87ec-4692-a6e2-43bf1e43889a">
<img width="630" alt="image" src="https://github.com/cooperlyt/keycloak-phone-provider/assets/3367820/586d7caf-4240-4b6f-b91c-e4fddc8743ae">

And I successfully registered one user by phone:

<img width="1235" alt="image" src="https://github.com/cooperlyt/keycloak-phone-provider/assets/3367820/dfc346e1-8a81-44a1-bfc8-04829db4db9b">

But when I try to log in with that user, it says the user does not exist!

<img width="1161" alt="image" src="https://github.com/cooperlyt/keycloak-phone-provider/assets/3367820/c6036f24-e791-45ad-9b73-671bdca39a34">

How could I fix that?

**Comment by Teut2711** [comment]
Facing the same issue

**Comment by Isshiki97** [comment]
I have the same problem
![1709791520228](https://github.com/cooperlyt/keycloak-phone-provider/assets/64454235/703b56dc-41f6-4f4b-81e6-2bbaa369348f)
![1709791520232](https://github.com/cooperlyt/keycloak-phone-provider/assets/64454235/9ca6515e-060c-4a9e-a4ed-7bcf5d03fee0)

**Comment by Isshiki97** [comment]
How could I fix that?
